apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: microservice
spec:
  # Este service es de tipo LoadBalancer y se tiene acceso a este nodo de K8s desde el exterior, mediante el puerto indicado en nodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
     app: gateway
     type: microservice