apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: microservice
spec:
  # Este deploy desplegará el pod 'gateway-pod' una única vez
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      type: microservice
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway
        type: microservice
    spec:
      # Este deploy contiene un unico tipo de pod: 'gateway-pod'
      # Este pod será desplegado una unica vez (según atributo 'replicas')
      containers:
        - name: gateway-app
          image: rsanvidal/serviciosapigateway:latest
          ports:
            - containerPort: 80