apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-libreria-deploy
  labels:
    name: microservice-libreria-deploy
    app: microservice
spec:
  # Este deploy desplegará el pod 'microservice-libreria-pod' dos veces
  replicas: 2
  selector:
    matchLabels:
      app: microservice-libreria
      type: microservice
  template:
    metadata:
      name: microservice-libreria-pod
      labels:
        app: microservice-libreria
        type: microservice
    spec:
      # Este deploy contiene un unico tipo de pod: 'microservice-libreria-pod'
      # Eso sí, este pod será desplegado dos veces (según atributo 'replicas')
      containers:
        - name: microservice-libreria-app
          # RSV. ANULADO image: rsanvidal/serviciosapilibreria:latest
          image: rsanvidal/serviciosapilibreria:v2.#{Build.BuildId}#
          ports:
            - containerPort: 80
          env:
            - name: MongoDb__ConnectionString
              value: mongodb://rsanvidal:$Rsanvidal2025@mongo-service:27017