apiVersion: v1
kind: Service
metadata:
  name: microservice-seguridad-service
  labels:
    name: microservice-seguridad-service
    app: microservice
spec:
  # Este service es de tipo ClusterIP, para impedir acceder directamente al pod 'microservice-seguridad-pod' 
  # NOTA. Un service de tipo LoadBalancer es accesible desde el exterior
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  # pod 'microservice-libreria-pod' 
  # Se relaciona este service con el pod mediante los labels definidos en el fichero microservice-seguridad-pod.yml
  selector:
    app: microservice-seguridad
    type: microservice