apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  containers:
    # Este pod aloja un único container (de Docker) llamado mongo (contiene la base de datos MongoDB)
    - name: mongo
      # Imagen obtenida desde Docker Hub
      image: mongo:4.2.21
      # Se utiliza el puerto 27017 para acceder a este container, porque este contenedor tiene alojado MongoDB, y esta base de datos tiene este puerto por defecto
      command:
      - /bin/bash
      - -c
      env:
      # Define las credenciales para acceder a la base de datos MongoDB
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "rsanvidal"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$Rsanvidal2025"
      ports:
        - containerPort: 27017